# -*- coding: utf-8 -*-
"""4112044027_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d00VZyuUeMDHA7-95uuVsOyj04QxMyhC
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體位址是:{id(x)}")